### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: nl4JbP8Cee4fcaa8cca166c9xB9SZBI7

origin=64999&destination=64942&weight=1000&courier=jne